---
- name: Ensure SteamCMD parent directory exists
  ansible.builtin.file:
    path: "{{ wares_dmz_steamcmd_directory }}"
    state: directory
    owner: "{{ wares_dmz_steamcmd_user }}"
    group: "{{ wares_dmz_steamcmd_group }}"
    mode: '0755'

- name: Loop through and install or update SteamCMD apps
  ansible.builtin.shell: |
    ./steamcmd.sh \
    +force_install_dir {{ wares_dmz_steamcmd_directory }}/{{ item.install_dir_name }} \
    +login anonymous \
    +app_update {{ item.id }} validate \
    +quit
  args:
    chdir: "{{ wares_dmz_steamcmd_directory }}"
    executable: "/bin/bash"
  loop: "{{ wares_dmz_steamcmd_apps }}"
  loop_control:
    label: "{{ item.install_dir_name }}"
  register: steamcmd_results
  become_user: "{{ wares_dmz_steamcmd_user }}"
  environment:
    HOME: "{{ wares_dmz_steamcmd_user_homedir }}"
    USER: "{{ wares_dmz_steamcmd_user }}"
  failed_when: "{{ stop_on_steamcmd_errors }}"

- name: Generate SteamCMD installation report
  ansible.builtin.set_fact:
    steamcmd_report: >-
      {{
        steamcmd_results.results | map('combine', {
          'app_name': item.item.install_dir_name,
          'app_id': item.item.id,
          'status': 'success' if item.rc == 0 else 'failed',
          'rc': item.rc,
          'stdout': item.stdout.split('\n')[-3:] | join('\n')  # seulement les dernières lignes
        }) | list
      }}

- name: Display SteamCMD installation report
  ansible.builtin.debug:
    var: steamcmd_report
